trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: ubuntu2004
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - bash: |
      echo Hello from Ubuntu 20.04
      lsb_release -d
      ls
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS

- job: buildimage
  pool:
   vmImage: 'ubuntu-20.04'
  steps:
  - task: NodeTool@0
    inputs:
     versionSpec: '8.x'

  - script: |
     npm install

- job: buildimage
  pool:
   vmImage: 'ubuntu-latest' 

  variables:
   imageName: 'pipelines-javascript-docker'

  steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
     repository: $(imageName)
     command: build
     Dockerfile: ./Dockerfile